spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

logging.level.com.shunya.demoopenfeign: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
